### ISSUE TITLE
feature: does it possible to set the exchange fees somewhere ?

### ISSUE THREAD

**Issue by yepla** [tommiehansen/gab#18]
Does it possible to set the correct value fees of the exchange we use for the backtest ?

**Comment by tommiehansen** [comment]
Yes, if you hack it and edit gab.class.php under system/.

Currently though no -- but the Gekko defaults is fine enough. Gabby isn't about squeezing the most performance possible out of something.

Might be added in the future though.

**Comment by tommiehansen** [comment]
This is now an option in your user configuration file.

See updated `user.config.sample.php` for reference.
