### ISSUE TITLE
How to make the nice lady be silent?

### ISSUE THREAD

**Issue by simpsus** [tommiehansen/gab#2]
a plus would be to have the error log not immediately go away when something goes wrong, but mainly .... where to disable the lady?

**Comment by tommiehansen** [comment]
That would indeed be a plus. No time has existed yet to fix that.
To silence 'the lady', mute your computers sound. It only plays 1x per start, can't be that annoying.

**Comment by simpsus** [comment]
combined with the output not staying on the console when it crashes I had to bash the run button to be able to read the output. Not a persistent issue
