### ISSUE TITLE
Update for Gekko 0.6

### ISSUE THREAD

**Issue by askmike** [tommiehansen/gab#22]
I've released gekko 0.6 which has some differences in the API. See the following links for details:

- https://gekko.wizb.it/docs/internals/server_api.html#POST-api-backtest
- https://github.com/askmike/gekko/releases/tag/v0.6.0

**Comment by SirTificate** [comment]
Tommie, I fixed the code but it seems like you're submerged. Just in case you are still reading this, would you mind to grant me the rights to merge the changes into your repo? 

Cheers

**Comment by tommiehansen** [comment]
@SirTificate  No, i'm not under the water. :)
But i had lots of stuff to do so my free time for these sort of things has been quite limited unfortunately. GAB took a lot of time. :)

I've sent you an invite to be a `Collaborator` (meaning you can commit/push to the GAB-repo)

**Comment by SirTificate** [comment]
Gab is now compatible with gekko 0.6. issue closed
