### ISSUE TITLE
Failing due to issue with PEAR when implementing on XAMPP

### ISSUE THREAD

**Issue by maxgebhardt** [tommiehansen/gab#29]
I'm trying to implement this on XAMPP, but get the following issue:

Warning: require(./views/header.php): failed to open stream: No such file or directory in C:\xampp\htdocs\system\conf.php on line 183

Fatal error: require(): Failed opening required './views/header.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\system\conf.php on line 183

PEAR is standard on XAMPP and there shouldn't be an issue with PEAR otherwise. I've tried a few potential workarounds by hardcoding the PEAR directory path, but no dice. Appreciate any feedback.

**Comment by r-schipper** [comment]
I'm getting the same error when trying to install gab on Windows. I have tried to get it working with wamp and a manual installation of apache and php but I'm getting the error in both cases. I have also installed PEAR in both cases. On mac it works great with MAMP, so I think it is an issue related to Windows.
@tommiehansen: do you have a idea how to fix this?

**Comment by SirTificate** [comment]
This has nothing to do with PEAR. The error message displays the configured include paths where it tried to locate the missing file. It looks like something is wrong with your path settings in your webserver configuration.

**Comment by tommiehansen** [comment]
@SirTificate is correct.

**Comment by jerryola1** [comment]
then give us the fix @tommiehansen
